name: EGP rate

on:
  schedule:
    - cron: "0,30 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install requests

      - run: python egp_rate_bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL: ${{ secrets.CHANNEL }}
          MESSAGE_ID: ${{ secrets.MESSAGE_ID }}

      - run: python usd_rate_bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL: ${{ secrets.USD_CHANNEL }}
          MESSAGE_ID: ${{ secrets.USD_MESSAGE_ID }}
